name: 'Tribe Package Zip'
description: 'Packages a zip for testing/release'
inputs:
  github-bot-token:
    description: 'Personal Access Token of user that can execute code reviews'
    required: true
    default: ''
outputs:
  zip:
    description: 'File name of the packaged zip file'
  results:
    description: 'Results of the packager'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-bot-token }}
